"""initial schema

Revision ID: 422bf1b3dbb6
Revises: 
Create Date: 2026-03-30 11:59:37.143373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422bf1b3dbb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.String(), nullable=False),
    sa.Column('agent_key', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('conviction', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('key_triggers', sa.JSON(), nullable=True),
    sa.Column('round_num', sa.Integer(), nullable=True),
    sa.Column('actual_direction', sa.String(), nullable=True),
    sa.Column('was_correct', sa.Integer(), nullable=True),
    sa.Column('market_snapshot', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_weight_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('agent_key', sa.String(), nullable=False),
    sa.Column('old_weight', sa.Float(), nullable=False),
    sa.Column('new_weight', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.String(), nullable=False),
    sa.Column('simulation_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('market_input', sa.JSON(), nullable=False),
    sa.Column('predicted_direction', sa.String(), nullable=False),
    sa.Column('predicted_conviction', sa.Float(), nullable=False),
    sa.Column('agents_output', sa.JSON(), nullable=False),
    sa.Column('actual_direction', sa.String(), nullable=True),
    sa.Column('check_timestamp', sa.String(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('simulations',
    sa.Column('simulation_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('market_input', sa.JSON(), nullable=False),
    sa.Column('agents_output', sa.JSON(), nullable=False),
    sa.Column('final_direction', sa.String(), nullable=False),
    sa.Column('final_conviction', sa.Float(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulations')
    op.drop_table('predictions')
    op.drop_table('agent_weight_history')
    op.drop_table('agent_predictions')
    # ### end Alembic commands ###
